### ISSUE TITLE
Not compatible with vlucas/phpdotenv 4.1.0

### ISSUE THREAD

**Issue by GarrettWeinberg** [ffraenz/private-composer-installer#17]
There is a dependancy issue with vlucas/phpdotenv 4.1.0. 
```Problem 1
    - Installation request for advanced-custom-fields/advanced-custom-fields-pro 5.8.7 -> satisfiable by advanced-custom-fields/advanced-custom-fields-pro[5.8.7].
    - Conclusion: remove vlucas/phpdotenv v4.1.0
    - Conclusion: don't install vlucas/phpdotenv v4.1.0
    - advanced-custom-fields/advanced-custom-fields-pro 5.8.7 requires ffraenz/private-composer-installer ^3.0 -> satisfiable by ffraenz/private-composer-installer[v3.0.0, v3.0.1].
    - ffraenz/private-composer-installer v3.0.0 requires vlucas/phpdotenv ^3.0 -> satisfiable by vlucas/phpdotenv[3.0.x-dev, 3.1.x-dev, 3.2.x-dev, 3.3.x-dev, 3.4.x-dev, 3.5.x-dev, 3.6.x-dev].
    - ffraenz/private-composer-installer v3.0.1 requires vlucas/phpdotenv ^3.0 -> satisfiable by vlucas/phpdotenv[3.0.x-dev, 3.1.x-dev, 3.2.x-dev, 3.3.x-dev, 3.4.x-dev, 3.5.x-dev, 3.6.x-dev].
    - Can only install one of: vlucas/phpdotenv[4.1.x-dev, 3.0.x-dev].
    - Can only install one of: vlucas/phpdotenv[4.1.x-dev, 3.1.x-dev].
    - Can only install one of: vlucas/phpdotenv[4.1.x-dev, 3.2.x-dev].
    - Can only install one of: vlucas/phpdotenv[4.1.x-dev, 3.3.x-dev].
    - Can only install one of: vlucas/phpdotenv[4.1.x-dev, 3.4.x-dev].
    - Can only install one of: vlucas/phpdotenv[4.1.x-dev, 3.5.x-dev].
    - Can only install one of: vlucas/phpdotenv[4.1.x-dev, 3.6.x-dev].
    - Installation request for vlucas/phpdotenv ^4.1.0 -> satisfiable by vlucas/phpdotenv[4.1.x-dev, v4.1.0].
```

relative composer dependancies:

```{
      "type": "package",
      "package": {
        "name": "advanced-custom-fields/advanced-custom-fields-pro",
        "version": "5.8.7",
        "type": "wordpress-plugin",
        "dist": {
          "type": "zip",
          "url": "https://connect.advancedcustomfields.com/index.php?a=download&p=pro&k={%ACF_PRO_KEY}&t={%version}"
        },
        "require": {
          "composer/installers": "^1.4",
          "ffraenz/private-composer-installer": "^3.0"
        }
      }
    }
  ],
  "require": {
    "php": ">=7.1",
    "composer/installers": "^1.8",
    "vlucas/phpdotenv": "^4.1.0",```

**Comment by abombelli** [comment]
Same here.

**Comment by ffraenz** [comment]
Thank you for reporting this issue! I'll provide an update for this package shortly.

**Comment by ffraenz** [comment]
A new major release `v4.0.0` of this package is now available depending on [vlucas/phpdotenv](https://github.com/vlucas/phpdotenv) `^4.0.0`. After changing the version in `composer.json` and running `composer update` the version conflicts should be resolved. Let me know if this works for you.

**Comment by GarrettWeinberg** [comment]
@ffraenz I verified that 4.0 is working. Thank you for fixing this and for putting out this pagkage!

**Comment by DanielYorwarth** [comment]
Still getting this issue using v5.3.0 (works with versions 3.5 and below)
